### ISSUE TITLE
Memory leak with node-cls

### ISSUE THREAD

**Issue by DusanMinic** [alfateam/node-cls#1] opened 2020-04-15 12:52 UTC
I just wanted to report, that we have a linear memory leak in our application from this library. Especially in high throughput services (200k+/min async operations).

**Comment by lroal** [comment] 2020-04-15 19:02
Thank you for submitting the issue.
Which node version are you using ?
Can you show me part of the code ? Or even better, create a small running example with the memory leak ?

**Comment by DusanMinic** [comment] 2020-04-17 11:47
The problem seems to be when there are many async operations. As far as I know, async_hooks keeps track of each one of them.

Here is a simple example:

```javascript
const cls = require('node-cls');
const WebSocket = require('ws');

const ws = new WebSocket('wss://ws-sandbox.coinapi.io/v1/');

ws.on('open', () => {
	ws.send(JSON.stringify({
		type: 'hello',
		apikey: 'API_KEY',
		heartbeat: true,
		subscribe_data_type: ['quote', 'trade'],
	}));
});

ws.on('message', async (message) => {
	// console.log(message);
});

```

I start the file with `--inspect` flag to track the heap size of the process. At bootup, memory is at around 5mb and it keeps rising constantly. After 2 min its already at 90mb. When I comment out `const cls = require('node-cls');` , the memory doesn't go up, it stays between 10mb and 20mb after 2 minutes.

Also, if I remove `async` keyword from `ws.on('message', async (message) => {`, even with **node-cls** required, there is **no** memory leak.

So it seems the problem is when there are a lot of async operations going on.

**Comment by lroal** [comment] 2020-04-18 06:49
Thank you. Yes, it keep tracks of the async calls. But they should be destroyed when nodejs fires the destroy event on the asyncId. That is, unless the async calls are nested/chained or there is  a bug in node-cls.

**Comment by lroal** [comment] 2020-04-20 10:15
It's an issue with node not firing the destroy event. I have reported it [https://github.com/nodejs/node/issues/32940](https://github.com/nodejs/node/issues/32940).

**Comment by DusanMinic** [comment] 2020-04-20 11:21
Great!

**Comment by lroal** [comment] 2020-08-06 06:12
What if If you add global.gc() ? Does memory usage go down ?
(You need to start with like this: node --expose-gc yourProgram.js)

**Comment by lroal** [comment] 2020-08-07 07:41
@DushanMinic , which version of node are you using ?

**Comment by DusanMinic** [comment] 2020-08-07 07:46
> What if If you add global.gc() ? Does memory usage go down ?
> (You need to start with like this: node --expose-gc yourProgram.js)

We've disabled request context completely on our project at the time being, I will probably try using this library at some point in the future when we get some more time for this.

I'm using v12.9.0.

**Comment by lroal** [comment] 2020-08-10 08:35
I have refactored and reduced the memory trace in version 1.0.6. If there are memory leaks, they must either be caused by nodejs not firing the destroy or an external lib (like ws) holding a reference that prevents GC.
Nodejs guys confirmed that they had no leaks.
I am closing the issue for now.

**Closed as completed by lroal** 2020-08-10 08:35 UTC
